apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promtail

resources:
  - ../../../../base/promtail
  - namespace.yaml

configMapGenerator:
  - name: promtail-env
    behavior: merge
    literals:
      - PROMTAIL_URL=https://logs-prod-us-central1.grafana.net/loki/api/v1/push
      - PROMTAIL_TENANT_ID=storetheindex
      - PROMTAIL_LABEL_OWNER=storetheindex
      - PROMTAIL_LABEL_ENV=dev
      - PROMTAIL_LABEL_REGION=us-east-2

secretGenerator:
  - name: promtail-auth
    behavior: replace
    envs:
      - auth.env
