apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

resources:
  - ../../../../../base/lookout
  - pod-monitor.yaml

patchesStrategicMerge:
  - deployment.yaml

configMapGenerator:
  - name: lookout-config
    behavior: create
    files:
      - config.yaml

images:
  - name: lookout
    newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/ipni/lookout
    newTag: 20230511104023-2cb718182431d507d5ee33defde11dedad466bd1

replicas:
  - name: lookout
    count: 0