apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: indexer
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - cera.prod.cid.contact
      secretName: cera-indexer-ingress-tls
  rules:
    - host: cera.prod.cid.contact
      http:
        paths:
          - path: /ingest
            pathType: Prefix
            backend:
              service:
                name: indexer
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: indexer
                port:
                  number: 3000
