apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-nginx
  - kube-system
  - flux-system
  - external-dns
  - cert-manager
  - cluster-autoscaler
  - monitoring
  - aws-ebs-csi-driver
  - promtail
  - external-snapshotter
