apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -stateless

commonLabels:
  app: dhstore-stateless

resources:
  - github.com/ipni/dhstore/deploy/kubernetes?ref=9939a3a8804356e6f5f18198dcfa8d75786f6223
  - pod-monitor.yaml

patchesStrategicMerge:
  - deployment.yaml

replicas:
  - name: dhstore
    count: 2

images:
  - name: dhstore
    newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/ipni/dhstore
    newTag: 20230705194338-aa1b4265230e18eac52ed01514c0ff31bb3c38b3
