apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhfind
spec:
  replicas: 5
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: dhfind
          args:
            - '--dhstoreAddr=http://dhstore.internal.prod.cid.contact/'
            - '--stiAddr=http://inga-indexer:3000/'
            - '--simulation=true'
            - '--simulationChannelSize=2000'
            - '--simulationWorkerCount=200'
          resources:
            limits:
              cpu: "2"
              memory: 1.5Gi
            requests:
              cpu: "2"
              memory: 1.5Gi
