apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2-m4-xl-2-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2a-m4-xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2b-m4-xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2c-m4-xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2a-c6a-8xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2b-c6a-8xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2c-c6a-8xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2a-c6a-8xl-2-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2b-c6a-8xl-2-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2c-c6a-8xl-2-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2c-r5n-2xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2a-r5n-2xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2c-r6a-xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2a-r6a-2xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2b-r6a-2xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2c-r6a-2xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2-c6a-8xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/prod-ue2-c6a-12xl-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::407967248065:user/masih
      username: masih
      groups:
        - system:masters
    - userarn: arn:aws:iam::407967248065:user/gammazero
      username: gammazero
      groups:
        - system:masters
    - userarn: arn:aws:iam::407967248065:user/will.scott
      username: will.scott
      groups:
        - system:masters
    - userarn: arn:aws:iam::407967248065:user/mayank.pandey
      username: mayank.pandey
      groups:
        - system:masters
    - userarn: arn:aws:iam::407967248065:user/ischasny
      username: ischasny
      groups:
        - system:masters
