# dhfind service is accessible only within K8S cluster VPC via:
#  - http://dhfind-alva.internal.dev.cid.contact
#
# See: https://github.com/ipni/dhfind
kind: Service
apiVersion: v1
metadata:
  name: dhfind
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    external-dns.alpha.kubernetes.io/access: private
    external-dns.alpha.kubernetes.io/hostname: dhfind-alva.internal.dev.cid.contact
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: dhfind-alva
