apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assigner
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
    - hosts:
        - assigner.dev.cid.contact
      secretName: assigner-ingress-tls
  rules:
    - host: assigner.dev.cid.contact
      http:
        paths:
          - path: /ingest
            pathType: Prefix
            backend:
              service:
                name: indexer
                port:
                  number: 3001
