apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/cluster-autoscaler

patchesStrategicMerge:
  - patch.yaml

replicas:
  - name: cluster-autoscaler
    count: 0
